CC := riscv64-unknown-elf-gcc

include ../bp/Makefile

train_twolayernet_fix16_run:
	spike pk ./train_twolayernet_fix16

train_twolayernet_float_run:
	spike pk ./train_twolayernet_float

train_twolayernet_run:
	spike pk ./train_twolayernet
